In [2]:
import numpy as np

# Problema 1

La fábrica de bicicletas Expend produce dos modelos de bicicletas, $M$ y $N$. La matriz $A$ nos indica las cantidades de acero y aluminio que requiere cada bicicleta, expresadas en kg según el modelo a producir, mientras que la matriz $B$ nos entrega un reporte de la cantidad de bicicletas producidas de ambos modelos para los dos primeros meses del año pasado.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
 & \ \ \ \  M & N
\end{matrix}  \\
&A= \begin{pmatrix}
1 & 2 \\
3 & 2 \\
\end{pmatrix} & \ \begin{matrix}
Acero\\
Aluminio
\end{matrix}\\
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ ene & feb &
\end{matrix} & \\
&B= \begin{pmatrix}
290 &  312 \\
 345 &  413 \\
\end{pmatrix} & \begin{matrix}
M\\
N
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Indique el orden de cada matriz. ¿Es posible determinar la multiplicación entre ambas matrices? Justifique.
2. Determine utilizando *Python* la matriz $C = A \cdot B$
3. Indique e interprete el valor de los elementos $c_{21}$ y $c_{11}$.

In [4]:
print("Respuesta 1:")
print("Si es posible pues ambas matrices son de orden 2x2")
A = np.array([
    [1,2],
    [3,2]
])
B = np.array([
    [290,312],
    [345,413]
])
print("")
print("Respuesta 2:")
C = A.dot(B)
print(f"C = \n{C}")
print("")
print("Respuesta 3:")
print(f"C_21: El total de aluminio usado en el mes de enero para ambos modelos fue: {C[1][0]}")
print(f"C_11: El total de acero usado en el mes de enero para ambos modelos fue: {C[0][0]}")

Respuesta 1:
Si es posible pues ambas matrices son de orden 2x2

Respuesta 2:
C = 
[[ 980 1138]
 [1560 1762]]

Respuesta 3:
C_21: El total de aluminio usado en el mes de enero para ambos modelos fue: 1560
C_11: El total de acero usado en el mes de enero para ambos modelos fue: 980


# Problema 2

Una pequeña cadena tiene restaurantes de comida rápida en Santiago, Concepción y Antofagasta, en los que vende hamburguesas, completos y mateadas. En un fin de semana, las cantidades de cada comida según cada sucursal se distribuyeron de acuerdo con la siguiente matriz $V$, donde las filas corresponden a los productos y las columnas a las sucursales, mientras que los precios, en pesos, de cada producto están expresados en la matriz $P$.

<br>

\begin{split}
V &= \begin{pmatrix}
 1300 &  900  &  800  \\
 2100 &  1700 &  1500 \\
 1500 &  1200 &  900  \\
\end{pmatrix}\\
\\
P &= \begin{pmatrix}
 4200 &  1500 & 3200 \\
\end{pmatrix}
\end{split}

<br>

Si $I = P \cdot V$

1. Indique el orden de cada matriz.
2. Determine utilizando *Python* la matriz $I$.
3. Indique e interprete el valor de los elementos $v_{32}$, $p_{12}$ e $i_{13}$.

In [13]:
V = np.array([
[1300 , 900  , 800 ],
[2100 , 1700 , 1500],
[1500 , 1200 , 900 ]
])

P = np.array([
[4200 ,  1500 , 3200 ]
])

print("Respuesta 1:")
print("V = orden 3x3")
print("P = orden 3x1")
print("")
print("Respuesta 2:")
I = P.dot(V)
print(f"I = \n{I}")
print("")
print("Respuesta 3:")
print(f"V_32: La cantidad total de malteadas vendidos en Concepción fue de: {V[2][1]}")
print(f"P_12: El precio de los completos es de: {P[0][1]}")
print(f"I_13: La ganancia de la sucursal en Antofagasta es de: {I[0][2]}")

Respuesta 1:
V = orden 3x3
P = orden 3x1

Respuesta 2:
I = 
[[13410000 10170000  8490000]]

Respuesta 3:
V_32: La cantidad total de malteadas vendidos en Concepción fue de: 1200
P_12: El precio de los completos es de: 1500
I_13: La ganancia de la sucursal en Antofagasta es de: 8490000


# Problema 3

Una fábrica, para un mismo tipo de artículo eléctrico produce $2$ modelos, $A$ y $B$. Las filas de la matriz $M$, en el orden mencionado, nos muestran la cantidad de transistores y resistores que se requieren por cada artículo, según cada modelo. Por otra parte, las filas de la matriz $Q$ nos reportan las cantidades producidas de cada modelo para las tres primeras semanas del mes pasado.

<br>

\begin{split}
M = \begin{pmatrix}
 9 &  14 \\
 4 &  5  \\
\end{pmatrix} \ \ \ \ \ \ \ \ Q = \begin{pmatrix}
 200 &  240 & 220 \\
 175 &  210 & 215 \\
\end{pmatrix}
\end{split}

<br>

Además, considere las matrices $G = M \cdot Q$ y $H = Q \cdot M$.

1. Indique el orden de $M$ y $Q$.
2. ¿Es posible calcular las matrices $G$ y $H$? Justifique.
3. Determine utilizando *Python* la matriz $G$ e interprete los elementos $g_{23}$  y $g_{12}$.
4. ¿Cuántos resistores se utilizaron durante las tres semanas?

In [3]:
M = np.array([
[9 , 14],
[4 , 5]
])

Q = np.array([
[200 ,  240 , 220 ],
[175 ,  210 , 215 ]
])

G = M.dot(Q)
print("Respuesta 1:")
print("M = orden 2x2")
print("Q = orden 2x3")
print("")
print("Respuesta 2:")
print(f"Si nos guiamos en que el número de columnas de la primera matriz debe coincidir con el número de filas de la segunda matriz, Sería viable calcular G y no es posible calcular H")
print("")
print("Respuesta 3:")
print(f"G = \n{G}")
print(f"G_23: La cantidad total de resistores requeridos para la semana 3 es de: {G[1][2]}")
print(f"G_12: La cantidad total de transistores requeridos para la semana 2 es de: {G[0][1]}")
print("")
print("Respuesta 4:")
print(f"Durante las 3 semanas se usaron {G[1][0]+G[1][1]+G[1][2]} resistores")


Respuesta 1:
M = orden 2x2
Q = orden 2x3

Respuesta 2:
Si nos guiamos en que el número de columnas de la primera matriz debe coincidir con el número de filas de la segunda matriz, Sería viable calcular G y no es posible calcular H

Respuesta 3:
G = 
[[4250 5100 4990]
 [1675 2010 1955]]
G_23: La cantidad total de resistores requeridos para la semana 3 es de: 1955
G_12: La cantidad total de transistores requeridos para la semana 2 es de: 5100

Respuesta 4:
Durante las 3 semanas se usaron 5640 resistores


# Problema 4

Una empresa de telecomunicaciones necesita optimizar la distribución de su infraestructura de red en Iquique, Santiago y Concepción. Las columnas de la matriz $R$, en el orden mencionado, representan la cantidad de routers y switches que se deben instalar en cada ciudad. La matriz $C$ muestra el costo de instalación, en pesos, de cada router y switch.

<br>

\begin{split}
R = \begin{pmatrix}
 50 &  70 \\
 80 &  110  \\
 60 &  90  \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 80000 \\
 45000 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* el costo total de instalación para cada ciudad y almacénalo en la matriz $T$.
2. ¿Cuál es la ciudad que tiene mayor costo de instalación?
3. Si se aplica un descuento del $10\%$ en el costo de instalación de los switches, calcula el nuevo costo total de instalación para cada ciudad.

In [6]:
R = np.array([
[50,70],
[80, 110],
[60, 90]
])

C = np.array([
[80000],
[45000]
])

T = R.dot(C)
print("Respuesta 1:")
print(f"T = \n{T}")
print("")
print("Respuesta 2:")
print(f"La ciudad con mayor costo de instalación es Santiago con un valor de {T[1][0]} pesos")
print("")
print("Respuesta 3:")
C[1][0] = 0.9 * C[1][0]
NT = R.dot(C)
print(f"El nuevo total es: \n{NT}")


Respuesta 1:
T = 
[[ 7150000]
 [11350000]
 [ 8850000]]

Respuesta 2:
La ciudad con mayor costo de instalación es Santiago con un valor de 11350000 pesos

Respuesta 3:
El nuevo total es: 
[[ 6835000]
 [10855000]
 [ 8445000]]


# Problema 5

Una empresa de servicios en la nube distribuye datos entre tres *Data Center*. La matriz $D$ muestra el volumen de datos (en terabytes) almacenados en cada *Data Center* durante los tres primeros meses del año. Mientras que la matriz $C$ muestra los costos (en dólares) de almacenamiento por terabyte en cada *Data Center*.

<br>

\begin{equation*}
\begin{matrix}
& \begin{matrix}
& \ \ \ \ \ \ \ DC_{1} &   DC_{2} & DC_{3}&
\end{matrix} & \\
&D = \begin{pmatrix}
100 & 150 & 200 \\
120 & 180 & 220 \\
140 & 210 & 250
\end{pmatrix} & \begin{matrix}
Ene\\
Feb\\
Mar
\end{matrix}
\end{matrix}
\ \ \ \ \ \ \ \ \ \ \ \ \ \
\begin{matrix}
& \begin{matrix}
\   
\end{matrix} & \\
&C = \begin{pmatrix}
50 \\
40 \\
30
\end{pmatrix}  \begin{matrix}
DC_{1}\\
DC_{2}\\
DC_{3}
\end{matrix}\\
\end{matrix}
\end{equation*}

<br>

1. Calcula utilizando *Python* la matriz $T = D \cdot C$.
2. Un trabajador indica que en febrero el costo por almacenamiento fue el más alto, ¿es cierta su afirmación?
3. Debido a la inflación, el costo de almacenamiento por terabyte aumenta en un $2,3\%$. Calcula el nuevo costo total de almacenamiento por mes e interprete cada uno de los elementos de la nueva matriz.

In [13]:
D = np.array([
[100 , 150 , 200 ],
[120 , 180 , 220],
[140 , 210 , 250]
])

C = np.array([
    [50],
    [40],
    [30]]
)

T = D.dot(C)
print("Respuesta 1:")
print(f"T = \n{T}")
print("")
print("Respuesta 2:")
print(f"Es falso pues el mes donde mas costo el almacenamiento fue en Marzo ({T[2][0]}).")
print("")
print(f"Respuesta 3:")
C = C*1.023
NT = D.dot(C)
print(f"La nueva matriz es: \n{NT}")
print(F"El nuevo costo total el mes:\nEnero: {NT[0][0]}\nFebrero: {NT[1][0]}\nMarzo: {NT[2][0]}")

Respuesta 1:
T = 
[[17000]
 [19800]
 [22900]]

Respuesta 2:
Es falso pues el mes donde mas costo el almacenamiento fue en Marzo (22900).

Respuesta 3:
La nueva matriz es: 
[[17391. ]
 [20255.4]
 [23426.7]]
El nuevo costo total el mes:
Enero: 17391.0
Febrero: 20255.399999999998
Marzo: 23426.699999999997


# Problema 6

Una compañía que fabrica un determinado producto, tiene $4$ plantas de producción y $5$ bodegas de almacenamiento. La matriz $T$ muestra las unidades de este producto que se generan mensualmente en la planta $i$ y que son transportadas a la bodega $j$, para quedar almacenadas allí durante el mes en que fueron producidas.

Además, la matriz $C$ detalla, para el primer semestre del presente año, el costo unitario (en dólares) de almacenamiento del producto durante el mes $j$ en la bodega $i$.

<br>

\begin{split}
T = \begin{pmatrix}
 500 &  400  &  300 & 200 & 100 \\
 600 &  500  &  400 & 300 & 200 \\
 700 &  600  &  500 & 400 & 300 \\
 800 &  700  &  600 & 500 & 400 \\
\end{pmatrix} \ \ \ \ \ \ C = \begin{pmatrix}
 5 &  6  &  7 &  8  &  9 & 6 \\
 4 &  5  &  6 &  7  &  8 & 7 \\
 3 &  4  &  5 &  6  &  7 & 9 \\
 2 &  3  &  4 &  5  &  6 & 6 \\
 8 &  5  &  6 &  3  &  7 & 5 \\
\end{pmatrix}
\end{split}

<br>

1. Determina la matriz $G = T \cdot C$.
2. Interpreta los elementos $t_{14}$, $c_{53}$ y $g_{35}$.
3. ¿Cuánto cuesta almacenar una unidad del producto en la bodega $4$ durante marzo de este año?
4. ¿Cuánto dinero gasta la empresa por almacenar la producción mensual de la planta $2$ durante el mes de abril?


In [15]:
T = np.array([
[500 ,  400  ,  300 , 200 , 100 ],
[600 ,  500  ,  400 , 300 , 200 ],
[700 ,  600  ,  500 , 400 , 300 ],
[800 ,  700  ,  600 , 500 , 400 ]
])

C = np.array([
[5 , 6  , 7 ,  8  ,  9 , 6],
[4 , 5  , 6 ,  7  ,  8 , 7],
[3 , 4  , 5 ,  6  ,  7 , 9],
[2 , 3  , 4 ,  5  ,  6 , 6],
[8 , 5  , 6 ,  3  ,  7 , 5]
])

G = T.dot(C)
print("Respuesta 1:")
print(f"G = \n{G}")
print("")
print("Respuesta 2:")
print(f"T_14: Para la planta 1 bodega 4, se generaron {T[0][3]} productos")
print(f"C_53: Para la bodega 5 el mes 3, el costo unitario es de {C[4][2]}")
print(f"G_35: Para la planta 3 el mes 5, el costo total de los productos generados será de {G[2][4]}")
print("")
print(f"Respuesta 3:")
print(f"Cuesta {C[3][2]} dolares")
print("")
print("Respuesta 4:")
print(f"La empresa gasta {G[1][3]} dolares por almacenar la producción mensual de abril en la planta 2")

Respuesta 1:
G = 
[[ 6200  7300  8800  9900 11700 10200]
 [ 8400  9600 11600 12800 15400 13500]
 [10600 11900 14400 15700 19100 16800]
 [12800 14200 17200 18600 22800 20100]]

Respuesta 2:
T_14: Para la planta 1 bodega 4, se generaron 200 productos
C_53: Para la bodega 5 el mes 3, el costo unitario es de 6
G_35: Para la planta 3 el mes 5, el costo total de los productos generados será de 19100

Respuesta 3:
Cuesta 4 dolares

Respuesta 4:
La empresa gasta 12800 dolares por almacenar la producción mensual de abril en la planta 2


# Problema 7

Una empresa dedicada al desarrollo de software, que cuenta con tres sucuersales, necesita renovar los siguientes implementos para su personal: laptop de alto rendimiento, monitor externo de alta resolución, teclado mecánico, mouse ergonómico y disco duro de alta capacidad. Para esto, decide cotizar con tres proveedores y así encontrar el precio más conveniente para realizar la compra. La matriz $F$, en el orden mencionado, indica la cantidad de artículos que necesita comprar para cada sucursal. La matriz $G$ indica el precio unitario (en miles de pesos) de cada producto por proveedor.

<br>

\begin{split}
F = \begin{pmatrix}
 7 &  6  &  15 & 17 & 18 \\
 5 &  10  &  20 & 13 & 12 \\
 8 &  4  &  12 & 18 & 9 \\
\end{pmatrix} \ \ \ \ \ \ G = \begin{pmatrix}
 1700 &  1750 &  1800 \\
  868 &  803  &  840  \\
  165 &  160  &  150  \\
  70  &  73  &   65   \\
  110 &  124  &  115  \\
\end{pmatrix}
\end{split}

<br>

1. Calcula utilizando *Python* la matriz $D = F \cdot G$.
2. Interpreta los elementos $d_{33}$ y $d_{21}$.
3. ¿Cuál es el proveedor más conveniente para realizar todas las compras?
4. Si escoge el proveedor más conveniente, ¿en qué sucursal deberá invertir más dinero por la renovación de los implementos?

In [19]:
F = np.array([
 [7 ,  6  ,  15 , 17 , 18],
 [5 ,  10  ,  20 , 13 , 12],
 [8 ,  4  ,  12 , 18 , 9]
])
G = np.array([
[1700 ,  1750 ,  1800],
[  868 ,  803  ,  840 ],
[  165 ,  160  ,  150 ],
[  70  ,  73  ,   65  ],
[  110 ,  124  ,  115 ]
])

D = F.dot(G)
print("Respuesta 1:")
print(f"D = \n{D}")
print("")
print("Respuesta 2:")
print(f"D_33: El costo total para la sucursal 3, usando el proovedor 3 será de {D[2][2]} miles de pesos")
print(f"D_33: El costo total para la sucursal 2, usando el proovedor 1 será de {D[1][0]} miles de pesos")
print("")
print("Respuesta 3:")
prov1 = sum(D[:][0])
prov2 = sum(D[:][1])
prov3 = sum(D[:][2])
print(f"Costos totales por proovedor: \nProovedor 1: {prov1}\nProovedor 2: {prov2}\nProovedor 3: {prov3}")
print(f"El proovedor mas conveniente es el proovedor 3")
print("")
print("Respuesta 4:")
print("En la sucursal numero 1")


Respuesta 1:
D = 
[[22753 22941 23065]
 [22710 22417 22625]
 [21302 21562 21765]]

Respuesta 2:
D_33: El costo total para la sucursal 3, usando el proovedor 3 será de 21765 miles de pesos
D_33: El costo total para la sucursal 2, usando el proovedor 1 será de 22710 miles de pesos

Respuesta 3:
Costos totales por proovedor: 
Proovedor 1: 68759
Proovedor 2: 67752
Proovedor 3: 64629
El proovedor mas conveniente es el proovedor 3

Respuesta 4:
En la sucursal numero 1


# Problema 8

Sea la matriz $A$:

<br>

\begin{split}
A = \begin{pmatrix}
 3 &  1  &  2 \\
 1 &  2  &  1 \\
 4 &  1  &  3 \\
\end{pmatrix}
\end{split}

<br>

1. Calcula, utilizando *Python*, la matriz $A^{-1}$.
2. Calcula la matriz $I = A \cdot A^{-1}$.
3. Calcula la matriz $I^{-1}$. Analiza este resultado, comparando con los resultados obtenidos en los ítems anteriores. ¿Puedes encontrar alguna relación para estas matrices?

In [6]:
A =  np.array([
    [3,1,2],
    [1,2,1],
    [4,1,3]
])

print("Respuesta 1:")
AI = np.linalg.inv(A)
print(f"Matriz inversa: \nAI:\n{AI}")
print("Respuesta 2:")
I = np.round(A.dot(AI))
print(f"Matriz identidad(A * A**-1): \nI:\n{I}")
print("Respuesta 3:")
II = np.linalg.inv(I)
print(f"Matriz inversa I : \nII:\n{II}")

Respuesta 1:
Matriz inversa: 
AI:
[[ 2.5 -0.5 -1.5]
 [ 0.5  0.5 -0.5]
 [-3.5  0.5  2.5]]
Respuesta 2:
Matriz identidad(A * A**-1): 
I:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Respuesta 3:
Matriz inversa I : 
II:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Problema 9

1. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
2x + y & = 7 \\
3x - 2y & = 21
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 2  &  1 \\
 3 & -2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 x \\
 y \\
\end{pmatrix} = \begin{pmatrix}
 7 \\
 21 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $x$ e $y$ que permiten satisfacer ambas ecuaciones simultáneamente.

<br>

2. Considera que el siguiente sistema de ecuaciones:

<br>

\begin{split}
h + m & = 60 \\
0,16h + 0,2m & = 11
\end{split}

<br>

$\hspace{1cm}$ Se puede escribir matricialmente como:

<br>

\begin{split}
\begin{pmatrix}
 1  &  1 \\
 0,16 & 0,2 \\
\end{pmatrix} \cdot \begin{pmatrix}
 h \\
 m \\
\end{pmatrix} = \begin{pmatrix}
 60 \\
 11 \\
\end{pmatrix}
\end{split}

<br>

* Utiliza la matriz inversa para encontrar los valores de $h$ y $m$ que permiten satisfacer el sistema de ecuaciones.

In [29]:
A = np.array([
    [2,1],
    [3,-2]
])
B = np.array([
        [7],
        [21]
])

AI = np.linalg.inv(A)
print(F"Matriz inversa de A = \n{AI}")

sol = AI.dot(B)
print(f"Los valores de x e y respectivamente son = \n{sol[0][0]:.0F} y {sol[1][0]:.0F}")
print("")
print("9.2:\n")
X = np.array([
    [1,1],
    [0.16,0.2]
])
Z = np.array([
    [60],
    [11]
])

XI = np.linalg.inv(X)
print(F"Matriz inversa de X = \n{XI}")

sol1 = XI.dot(Z)
print(f"Los valores de h e m respectivamente son = \n{sol1[0][0]:.0F} y {sol1[1][0]:.0F}")

Matriz inversa de A = 
[[ 0.28571429  0.14285714]
 [ 0.42857143 -0.28571429]]
Los valores de x e y respectivamente son = 
5 y -3

9.2:

Matriz inversa de X = 
[[  5. -25.]
 [ -4.  25.]]
Los valores de h e m respectivamente son = 
25 y 35


# Problema 10

Considera los siguientes sistemas de ecuaciones:

<br>

**a)**
\begin{split}
2m + 4p & = 2900 \\
3m + 3p & = 3150
\end{split}
<br>
<br>
**b)**
\begin{split}
n + v & = 160 \\
50n + 300v & = 23000
\end{split}

<br>

1. Escribe ambos sistemas de ecuaciones de forma matricial.
1. Utiliza la matriz inversa para calcular las soluciones de ambos sistemas de ecuaciones.




In [ ]:
A = np.array()

# Problema 11

Una persona tiene $\$8000$ en monedas de $\$10$ y de $50$. El sistema de ecuaciones que representa la situación es el siguiente:

<br>

\begin{split}
x + y & = 200 \\
10x + 50y & = 8000
\end{split}

<br>

1. ¿Qué representa cada variable?
2. Explica qué representa cada una de las ecuaciones del sistema.
3. ¿Cuántas monedas de $\$10$ y de $\$50$ tiene?

In [18]:
print("Respuesta 1:")
print("x -> Representa la cantidad de monedas de 10")
print("y -> Representa la cantidad de monedas de 50")
A= np.array([
    [1,1],
    [10,50]
])
B = np.array([
    [200],
    [8000]
])

AI = np.linalg.inv(A)
print("")
print("Respuesta 2:")
print("La primera ecuación corresponde a la suma entre cantidad de monedas que hay entre las de 10 y las de 50")
print("La segunda ecuación corresponde a la suma total entre las monedas de 10 y 50")
valor = np.round(AI.dot(B))
print("")
print("Respuesta 3:")
print(f"Hay {valor[0][0]} monedas de $10 y {valor[1][0]} monedas de $50")

Respuesta 1:
x -> Representa la cantidad de monedas de 10
y -> Representa la cantidad de monedas de 50

Respuesta 2:
La primera ecuación corresponde a la suma entre cantidad de monedas que hay entre las de 10 y las de 50
La segunda ecuación corresponde a la suma total entre las monedas de 10 y 50

Respuesta 3:
Hay 50.0 monedas de $10 y 150.0 monedas de $50


# Problema 12

En una granja hay $132$ animales entre patos y vacas. En total hay $402$ patas. El sistema que modela la situación planteada es:

<br>

\begin{split}
p + v & = 132 \\
2p + 4v & = 402
\end{split}

<br>

1. ¿Qué representan las incógnitas del sistema?
2. ¿Cuántos patos hay?

In [20]:
print("Respuesta 1:")
print("p -> Representa la cantidad de patos")
print("v -> Representa la cantidad de vacas")
A= np.array([
    [1,1],
    [2,4]
])
B = np.array([
    [132],
    [402]
])

AI = np.linalg.inv(A)

valor = np.round(AI.dot(B))
print("")
print("Respuesta 2:")
print(f"Hay {valor[0][0]} patos")

Respuesta 1:
p -> Representa la cantidad de patos
v -> Representa la cantidad de vacas

Respuesta 2:
Hay 63.0 patos


# Problema 13

Luis compró $5$ cables USB y $6$ pendrives, en total canceló $\$82.890$. Pablo compró a los mismos precios $3$ cables USB y $7$ pendrives, y canceló $\$59.900$.

El sistema que modela el problema es:

<br>

\begin{split}
5x + 6y &= 82890 \\
3x +  7y &= 59900
\end{split}

<br>


1. ¿Qué representa cada incógnita en el contexto del problema?
2. Determina cuánto pagaron por cada cable USB.

In [21]:
print("Respuesta 1:")
print("x -> Representa el precio del cable usb (unitario)")
print("y -> Representa el precio del pendrive (unitario)")
A = np.array([
    [5,6],
    [3,7]
])
B = np.array([
    [82890],
    [59900]
])

AI = np.linalg.inv(A)

valor = np.round(AI.dot(B))
print("")
print("Respuesta 2:")
print(f"El valor del usb sera de {valor[0][0]}")

Respuesta 1:
x -> Representa el precio del cable usb (unitario)
y -> Representa el precio del pendrive (unitario)

Respuesta 2:
El valor del usb sera de 12990.0
