In [1]:
#Expresión es a1(primer termino)+ diferencia * (n-1), esto para sucesiones aritmeticas
#Expresion es a1(primer termino) * (r(razón) ** (n-1))
import numpy as np

Sea una sucesión cuyos tres primeros términos son 200, 224 y 248. Si la sucesión mantiene el mismo patrón de crecimiento sucesivamente.



1.- El valor del término que ocupa el lugar 36 en esta sucesión es:



In [3]:
a1 = 200;
d = 24
#a_36 = a1 + d * (36-1)
print(f"Respuesta: {a1 + d * (36-1)}")

Respuesta: 1040


2.- ¿Cuál es la suma de los primeros 36 términos de esta sucesión? 



In [5]:
lista = []
for i in range(36):
    n = i+1
    resultado = a1 + d * (n-1)
    lista.append(resultado)
print(f"El resultado de la suma de los primeros 36 términos es de {sum(lista)}")

El resultado de la suma de los primeros 36 términos es de 22320



Una cuenta de ahorros proporciona un interés mensual del 1,2%. La cuenta se abre con $2.000.000. En este contexto, se define a subíndice n como el saldo en pesos que presenta esta cuenta de ahorros transcurridos n meses.

1.- La expresión algebraica que permite calcular cada término de la sucesión a subíndice n es:

In [6]:
print(f"2.000.000 * 1.012**n")

2.000.000 * 1.012**n


2.- El saldo aproximado, en la cuenta de ahorros al cabo de 9 meses será:

In [8]:
print(f"El saldo tras 9 meses será: {(2000000 * 1.012**9):.0f}")

El saldo tras 9 meses será: 2226664



Una empresa de tecnología está optimizando sus servidores. Para ello, mide cada mes las transacciones por segundo (TPS) de sus servidores. Se ha obtenido que el segundo mes, el rendimiento del servidor es 1.066 TPS y el quinto mes, el rendimiento es de 8.528 TPS.

1.- Si el rendimiento de los servidores crece a razón constante, ¿cuál es el rendimiento de un servidor el noveno mes? 



In [20]:
#Expresion es a1(primer termino) * (r(razón) ** (n-1))
"""
1066 = a1 * r **(2-1) ->  1066 = a1 * r **(1)
8528 = a1 * r **(5-1) ->  8528 = a1 * r **(4)

Dividimos el de abajo por el de arriba para sacar la razon
8258/1066 = a1*r**4/a1*r**1 -> 8258/1066 = r**4/r**1 -> 8258/1066 = r**3 -> r = (8258/1066)**1/3
"""
r = (8528/1066)**(1/3)
a1 = 1066 / r

print(f"a9 = {a1} * {r} ** ({9}-{1}) -> {(a1 * r ** (9-1)):.0f}")

a9 = 533.0 * 2.0 ** (9-1) -> 136448


2- Si el rendimiento de los servidores crece a razón constante, ¿en qué mes el rendimiento de un servidor es de 34.112 TPS? 



In [22]:
print(f"El lugar para el número 34.112 será: {round(((np.log((34112/a1))/np.log(r))+1),1)}")


El lugar para el número 34.112 será: 7.0


13.-

14.- ¿Cuántos minutos debe ejecutarse el Servicio A en cada servidor?



In [7]:
N = np.array([
    [2,1],
    [3,-2]
])
M = np.array([
    [10],
    [8]
])
NI = np.linalg.inv(N)
Sol = NI.dot(M)
print(f"Respuesta = {Sol}")

Respuesta = [[4.]
 [2.]]


15 a 19


In [9]:
A = np.array([
    [2,3],
    [1,2]
])
AI = np.linalg.inv(A)
print(AI)

[[ 2. -3.]
 [-1.  2.]]


In [10]:
A = np.array([
    [2,3],
    [1,2]
])
AT = A.T
print(AT)

[[2 1]
 [3 2]]


In [11]:
S = A + AT
print(S)

[[4 4]
 [4 4]]


20.-

In [12]:
A = np.array([
    [2,3],
    [1,4]
])
b = np.array([
    [52],
    [56]
])
AI = np.linalg.inv(A)
Sol = AI.dot(b)
print(f"Respuesta = {Sol}")

Respuesta = [[ 8.]
 [12.]]
